Hw05 parallel execution
Vasilui/otus_homework pull request #5
Opened 2023-09-21 12:42 UTC by Vasilui

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-09-22 04:18 UTC, dshemin requested changes

2023-09-22 04:18 UTC, dshemin commented on hw04_lru_cache/go.mod
>  go 1.19
Критично:

Не исправлено название модуля, это надо делать в каждом задании.

2023-09-22 04:18 UTC, dshemin commented on hw05_parallel_execution/run.go
> +func Work(tasks <-chan Task, results chan<- error, stop <-chan struct{}, wg *sync.WaitGroup) {
Важно:

Не надо добавлять sync.WaitGroup в качестве зависимости, она ни как не влияет на логику выполнения, только усложняет использование и тестирование.

2023-09-22 04:18 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		br := true
Важно:

Зачем нам тут этот флаг? Мы можем просто сделать break из вложенного цикла.

2023-09-22 04:18 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	jobs := make(chan Task, len(tasks))
Важно:

Нет проверки на то, что n < 0. Надо так же будет добавить тест.

2023-09-22 04:18 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for a := 1; a <= len(tasks); a++ {
Критично:

Не совсем верное решение, нужно сделать так, чтобы по достижению нужного количества ошибок мы сразу завершали выполнение.

2023-09-22 07:07 UTC, Vasilui commented on hw05_parallel_execution/run.go
> +func Work(tasks <-chan Task, results chan<- error, stop <-chan struct{}, wg *sync.WaitGroup) {
Согласен, убрал из зависимостей

2023-09-22 07:08 UTC, Vasilui commented on hw05_parallel_execution/run.go
> +		br := true
Можно, да, но тогда пришлось делать именованных цикл, не знаю, что и лучше, но поправил

2023-09-22 15:23 UTC, Vasilui commented on hw05_parallel_execution/run.go
> +	for a := 1; a <= len(tasks); a++ {
Вот ту не совсем понял, но ведь если я не дождусь выполнения, то таски не завершаться, разве нет?

2023-09-26 17:28 UTC, dshemin approved these changes

2023-09-26 17:28 UTC, dshemin approved these changes

2023-09-26 18:41 UTC, merged